### ISSUE TITLE
Starting a multiprocessing Process targeting sensor.get_data results in EOFError: Ran out of input

### ISSUE THREAD

**Issue by NAkbulut** [Neehier/behaviorbank#1]
Bug report
---

**Related problem to feature request**

Starting a Process using multiprocessing, which targets the get_data function from the object of the Sensor class, always results in an `EOFError: Ran out of input`. The function does not start.

**Dependencies to the feature request**

This issue has only been tested within the scope of the `bb-web-scraper` file.

**Additional context**

``` py
def read_data(db, sensors):
    for sensor in sensors:
        sensor.set_driver()    
        sensor_process = Process(target=sensor.get_data)
        sensor_process.start()
```

``` py
def get_data(self):
    self.driver.get(self.url)
    thermal = self.driver.find_element(By.XPATH, '//div[@class="col-6 pb-20"]')
    conditions = self.driver.find_element(By.XPATH, '//div[@class="col-6 pb-20 pl-50"]')
    sdatetime, stemperature, shumidity, sprecipitation, swind = self.parse_data(conditions, thermal)
    return sdatetime, stemperature, shumidity, sprecipitation, swind
```

**Comment by NAkbulut** [comment]
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\ipdamh\bb-web-scraper.py", line 30, in <module>
    main()
  File "C:\Users\user\Documents\ipdamh\bb-web-scraper.py", line 26, in main
    loading_process = Process(target=check_load(None, sensors))
  File "C:\Users\user\Documents\ipdamh\bb-web-scraper.py", line 8, in check_load
    read_data(db, sensors)
  File "C:\Users\user\Documents\ipdamh\bb-web-scraper.py", line 16, in read_data
    sensor_process.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_createenviron.<locals>.encodekey'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by NAkbulut** [comment]
**Possible issue**

The use of a single `selenium.webdriver` instance for parallel tasks.

**Possible fix**

Initialize a separate `selenium.webdriver` instance for each process.

**Source**

https://stackoverflow.com/questions/52303359/python-pickling-issues-with-pathos-and-selenium
